### ISSUE TITLE
Migrate Travis from GH Webhooks -> GH WebApps

### ISSUE THREAD

**Issue by tomschr** [openSUSE/doc-ci#7]
## Problem
End of year, GH announced to discontinue Webhooks in favor of Webapps. We need to take care of our repositories and migrate them.

This is an issue to remind us for this process.

## Solution

* It seems, Travis does this in some way automatically as described here:

   https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

* Another project (Ruby) which could interesting too:

  https://github.com/travis-ci/travis_migrate_to_apps

**Comment by sknorr** [comment]
Update Jan 2020:

* We are still on travis-ci.org
* Travis CI, the company, reverted their decision to force everyone to use the GitHub app & travis-ci.com at the same time ([see](https://blog.travis-ci.com/2019-01-31-github-services-integration-deprecation))
* **It is unclear if or when travis-ci.org will be turned off.** I see absolutely no information on that anywhere.
* I successfully set up a new repo (SUSE/doc-vmdp) with travis-ci.org in Aug 2019, so **setting up new repos still works**
* The SUSE org on GitHub does not allow using the travis-ci.com GitHub app. **Trying to move toward using the Travis CI GitHub app is a waste of time.**
* It is unclear to me whether travis-ci.com can be used with webhooks.
* GitHub Actions now provides GitHub-built-in CI tooling. However, moving is a bunch of work because the configuration is completely different.

-> Let's just sit this out for as long as possible and not waste effort.

Closing this issue.
